# Generated by Django 4.1.6 on 2023-03-01 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_cliente_potencial_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cliente_potencial',
            new_name='potential_client',
        ),
    ]
