# Generated by Django 4.1.6 on 2023-03-01 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_rename_cliente_potencial_potential_client'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='potential_client',
            new_name='contact',
        ),
    ]
