# Generated by Django 4.1.6 on 2023-03-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_rename_potential_client_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ES', models.CharField(max_length=100)),
                ('name_EN', models.CharField(max_length=100)),
                ('ISO_2', models.CharField(max_length=10)),
                ('ISO_3', models.CharField(max_length=10)),
                ('code_phone', models.CharField(max_length=10)),
            ],
        ),
    ]
