# Generated by Django 4.1.6 on 2023-03-01 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_country'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country',
            new_name='Code_Phone_Country',
        ),
    ]
